/**
 * CLASSES PRONTAS (presets) — o antídoto à ficha em branco.
 *
 * O sistema alcança 3.215 elementos. Ninguém começa daí. Um preset é uma
 * ficha inteira já distribuída, com uma skill montada, que a pessoa carrega
 * com um clique e depois desmonta à vontade: **ponto de partida, não trilho**.
 *
 * Isto aqui é DADO PURO. Nada de `criarPersonagem`/`investir*` — os presets
 * moravam na UI e isso punha conteúdo de jogo na camada de apresentação.
 * Quem transforma este dado em `Personagem` é `src/engine/presets.ts`.
 *
 * Nada aqui importa do motor. As formas de configuração de skill vivem em
 * `formatos.ts`, dentro do próprio registro, justamente para que este arquivo
 * não precise apontar para `engine/`.
 *
 * O CAMPO `promete` É O CONTRATO. Cada preset declara o que deve acontecer
 * quando é carregado — quais arquétipos abrem, quais elementos passam a
 * existir, quais capacidades ficam disponíveis. `verificarPreset` roda o
 * motor e confere. Um preset que mente quebra a suíte de testes, e é por
 * isso que a lista pode crescer sem virar folclore.
 */

import type { ElementoBaseId, ElementoId } from './elementos';
import type { EscolaId } from './escolas';
import type { RecursoId } from './recursos';
import type { TalentoId } from './talentos';
import type { ProfissaoId } from './profissoes';
import type { ModificadorId } from './modificadores';
import type { SkillConfig } from './formatos';

/**
 * Papel em grupo. É a primeira pergunta de quem escolhe uma classe pronta
 * ("quero bater de longe", "quero segurar a linha"), então é o eixo de
 * agrupamento da galeria.
 */
export type PapelPreset =
  | 'area'
  | 'foco'
  | 'linha_de_frente'
  | 'suporte'
  | 'controle'
  | 'invocador'
  | 'oficio';

export const ROTULO_PAPEL: Record<PapelPreset, string> = {
  area: 'Dano em área',
  foco: 'Dano concentrado',
  linha_de_frente: 'Linha de frente',
  suporte: 'Suporte',
  controle: 'Controle',
  invocador: 'Invocador',
  oficio: 'Ofício',
};

/**
 * 1 = duas bases e uma skill direta; 2 = combinação de 3 ou mecânica extra;
 * 3 = quádrupla, fusão ou encadeamento de modificadores.
 */
export type Complexidade = 1 | 2 | 3;

export const ROTULO_COMPLEXIDADE: Record<Complexidade, string> = {
  1: 'Direto',
  2: 'Intermediário',
  3: 'Avançado',
};

/** Uma criatura que o preset já traz capturada (e, se vínculo > 0, domada). */
export interface BestiarioPreset {
  criaturaId: string;
  vinculo: number;
}

/** Fusão de exemplo que acompanha o preset, já montada na aba Fusão. */
export interface FusaoPreset {
  nome: string;
  componentes: SkillConfig[];
  escolaDominante?: EscolaId;
  modificadores?: ModificadorId[];
}

/**
 * O contrato do preset. Verificado contra o motor — não é documentação.
 */
export interface PromessaPreset {
  /** Ids de arquétipo que a ficha DEVE desbloquear por inteiro. */
  arquetipos: string[];
  /** Elementos que devem existir na ficha (nível efetivo > 0). */
  elementos?: ElementoId[];
  /** Arquétipos alcançados apenas como meia-identidade (diluídos). */
  arquetiposDiluidos?: string[];
}

export interface PresetDef {
  id: string;
  /** Nome da CLASSE (é o que aparece no card). */
  nome: string;
  /** Nome próprio do personagem exemplo — dá cara à ficha. */
  personagem: string;
  /** Uma frase: o que essa classe faz. Lida em 3 segundos. */
  descricao: string;
  /**
   * A mecânica que este preset existe para demonstrar. Depois de carregado,
   * a interface aponta para cá. Presets são o material didático do sistema.
   */
  ensina: string;
  papel: PapelPreset;
  complexidade: Complexidade;
  /** De onde a fantasia vem, quando vem de algum lugar conhecido. */
  referencia?: string;

  elementos: Partial<Record<ElementoBaseId, number>>;
  escolas: Partial<Record<EscolaId, number>>;
  recursos: Partial<Record<RecursoId, number>>;
  talentos?: Partial<Record<TalentoId, number>>;
  profissoes?: Partial<Record<ProfissaoId, number>>;
  bestiario?: BestiarioPreset[];

  skill: SkillConfig;
  fusao?: FusaoPreset;

  promete: PromessaPreset;
}

// ---------------------------------------------------------------------------
// Atalhos de escrita. Só reduzem repetição; não escondem regra nenhuma.
// ---------------------------------------------------------------------------

const sk = (
  base: Partial<SkillConfig> &
    Pick<SkillConfig, 'nome' | 'elemento' | 'escola' | 'fontes'>,
): SkillConfig => ({
  energia: 20,
  tempoConjuracaoSegundos: 1.5,
  alcanceMetros: 10,
  area: { tipo: 'unico' },
  entrega: { tipo: 'instantaneo' },
  ...base,
});

const fonte = (recurso: RecursoId, proporcao = 100) => ({ recurso, proporcao });
const circulo = (raioMetros: number) => ({ tipo: 'circulo', raioMetros }) as const;
const continuo = (duracaoSegundos: number) =>
  ({ tipo: 'continuo', duracaoSegundos }) as const;

// ---------------------------------------------------------------------------
// A lista
// ---------------------------------------------------------------------------

export const PRESETS: PresetDef[] = [
  // ======================= complexidade 1: dois elementos ===================
  {
    id: 'lavamante',
    nome: 'Lavamante',
    personagem: 'Brasa, o Lavamante',
    descricao: 'Abre o chão em lava debaixo de um grupo inteiro. Fogo + Terra.',
    ensina: 'Dois elementos base viram um terceiro — Fogo + Terra = Lava.',
    papel: 'area',
    complexidade: 1,
    elementos: { fogo: 14, terra: 14 },
    escolas: { conjuracao: 14 },
    recursos: { mana: 10 },
    talentos: { area_ampliada: 3, impacto_imediato: 2 },
    skill: sk({
      nome: 'Erupção',
      elemento: 'lava',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
    }),
    promete: { arquetipos: ['lavamante'], elementos: ['lava'] },
  },
  {
    id: 'tempestario',
    nome: 'Tempestário',
    personagem: 'Zael, o Tempestário',
    descricao: 'Parte o céu sobre um campo inteiro. Ar + Eletricidade.',
    ensina: 'Área grande dilui o dano por alvo — o orçamento é redistribuído.',
    papel: 'area',
    complexidade: 1,
    elementos: { ar: 13, eletricidade: 13 },
    escolas: { conjuracao: 12 },
    recursos: { mana: 8 },
    talentos: { area_ampliada: 2 },
    skill: sk({
      nome: 'Céu Partido',
      elemento: 'tempestade',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(8),
    }),
    promete: { arquetipos: ['tempestario'], elementos: ['tempestade'] },
  },
  {
    id: 'necromante',
    nome: 'Necromante',
    personagem: 'Vesper, a Necromante',
    descricao: 'Ergue uma legião de esqueletos que luta no seu lugar. Morte + Evocação.',
    ensina: 'Skills podem exigir CAPACIDADE de arquétipo, não só nível.',
    papel: 'invocador',
    complexidade: 1,
    referencia: 'D&D, Diablo',
    elementos: { morte: 18, sombra: 10 },
    escolas: { evocacao: 14 },
    recursos: { mana: 10 },
    talentos: { enxame: 3 },
    skill: sk({
      nome: 'Legião de Ossos',
      elemento: 'morte',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 3,
      capacidadeExigida: 'evocar_mortos_vivos',
    }),
    promete: { arquetipos: ['necromante'], elementos: ['espectro'] },
  },
  {
    id: 'paladino',
    nome: 'Paladino',
    personagem: 'Aurelia, a Paladina',
    descricao: 'Segura a linha e protege quem está atrás. Luz + Vigor, movido a Fé.',
    ensina: 'Fé como fonte — recurso que paga mais barato quanto mais devoto.',
    papel: 'linha_de_frente',
    complexidade: 1,
    referencia: 'D&D, WoW',
    elementos: { luz: 15, vida: 15, marcial: 15 },
    escolas: { combate_fisico: 12, benca: 8 },
    recursos: { fe: 10 },
    talentos: { egide: 2, postura_inabalavel: 2 },
    skill: sk({
      nome: 'Aura da Bravura',
      elemento: 'bravura',
      escola: 'benca',
      fontes: [fonte('fe')],
      tempoConjuracaoSegundos: 2,
      area: circulo(4),
      entrega: continuo(10),
    }),
    promete: { arquetipos: ['paladino'], elementos: ['bravura'] },
  },
  {
    id: 'berserker',
    nome: 'Berserker',
    personagem: 'Korg, o Berserker',
    descricao: 'Bate mais forte quanto mais apanha. Vigor + Fogo, movido a Fúria.',
    ensina: 'Fúria é o recurso que cresce na luta, não antes dela.',
    papel: 'linha_de_frente',
    complexidade: 1,
    referencia: 'D&D, Diablo',
    elementos: { fogo: 15, vida: 15, marcial: 15 },
    escolas: { combate_fisico: 14 },
    recursos: { furia: 10 },
    talentos: { golpe_devastador: 2, sede_de_batalha: 2 },
    skill: sk({
      nome: 'Golpe Fervente',
      elemento: 'fervor',
      escola: 'combate_fisico',
      fontes: [fonte('furia')],
      energia: 25,
      tempoConjuracaoSegundos: 1,
      alcanceMetros: 0,
    }),
    promete: { arquetipos: ['berserker'], elementos: ['fervor'] },
  },
  {
    id: 'santo',
    nome: 'Santo Guardião',
    personagem: 'Ilya, a Santa Guardiã',
    descricao: 'Cura o grupo inteiro e sustenta a cura no tempo. Luz + Vida.',
    ensina: 'Entrega contínua espalha o orçamento no tempo em vez do espaço.',
    papel: 'suporte',
    complexidade: 1,
    elementos: { luz: 14, vida: 14 },
    escolas: { benca: 14 },
    recursos: { fe: 10 },
    talentos: { vinculo_de_grupo: 2, egide: 2 },
    skill: sk({
      nome: 'Graça Plena',
      elemento: 'santidade',
      escola: 'benca',
      fontes: [fonte('fe')],
      energia: 24,
      tempoConjuracaoSegundos: 2,
      area: circulo(4),
      entrega: continuo(10),
    }),
    promete: { arquetipos: ['santo_guardiao'], elementos: ['santidade'] },
  },
  {
    id: 'toxicologista',
    nome: 'Toxicologista',
    personagem: 'Mordra, a Toxicologista',
    descricao: 'Envenena e deixa o dano correr sozinho. Água + Morte.',
    ensina: 'Dano ao longo do tempo entrega MAIS total, diluído na duração.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'PoE, Ragnarok',
    elementos: { agua: 14, morte: 14 },
    escolas: { maldicao: 12 },
    recursos: { mana: 8 },
    talentos: { dano_ao_longo_do_tempo: 3, contagio: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Névoa Corrosiva',
      elemento: 'veneno',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 24,
      tempoConjuracaoSegundos: 2,
      area: circulo(5),
      entrega: continuo(12),
    }),
    promete: { arquetipos: ['toxicologista'], elementos: ['veneno'] },
  },
  {
    id: 'atirador_fantasma',
    nome: 'Atirador Fantasma',
    personagem: 'Nera, a Atiradora Fantasma',
    descricao: 'Atira através de paredes e acerta o que não vê. Sombra + Morte.',
    ensina: 'Longo alcance troca área por precisão: alcance é uma escola.',
    papel: 'foco',
    complexidade: 1,
    elementos: { sombra: 14, morte: 14 },
    escolas: { longo_alcance: 14 },
    recursos: { mana: 9 },
    talentos: { olho_de_aguia: 3, alcance_estendido: 3 },
    skill: sk({
      nome: 'Tiro Fantasma',
      elemento: 'espectro',
      escola: 'longo_alcance',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 1.8,
      alcanceMetros: 35,
      capacidadeExigida: 'tiro_fantasma',
    }),
    promete: { arquetipos: ['atirador_fantasma'], elementos: ['espectro'] },
  },
  {
    id: 'xama_totemico',
    nome: 'Xamã Totêmico',
    personagem: 'Ogumar, o Xamã',
    descricao: 'Finca totens que reforçam quem estiver por perto. Eletricidade + Luz.',
    ensina: 'Sinergias transbordam: pontos em um elemento sobem os vizinhos.',
    papel: 'suporte',
    complexidade: 1,
    referencia: 'WoW',
    elementos: { eletricidade: 14, luz: 12 },
    escolas: { benca: 12, conjuracao: 6 },
    recursos: { mana: 10 },
    talentos: { persistencia: 3, vinculo_de_grupo: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Totem do Trovão',
      elemento: 'fulgor',
      escola: 'benca',
      fontes: [fonte('mana')],
      energia: 22,
      tempoConjuracaoSegundos: 2,
      area: circulo(6),
      entrega: continuo(14),
      capacidadeExigida: 'fincar_totens',
    }),
    promete: { arquetipos: ['xama_totemico'], elementos: ['fulgor'] },
  },
  {
    id: 'espadachim_arcano',
    nome: 'Espadachim Arcano',
    personagem: 'Sil, a Espadachim Arcana',
    descricao: 'Imbui a lâmina de magia e bate de perto. Arcano + Marcial + Vigor.',
    ensina: 'Marcial combina com QUALQUER elemento e vira uma arma nova.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'FF, ToS',
    elementos: { arcano: 15, marcial: 15, vida: 15 },
    escolas: { combate_fisico: 12 },
    recursos: { mana: 8 },
    talentos: { endossar_elemento: 3, sequencia_marcial: 2 },
    skill: sk({
      nome: 'Estocada Encantada',
      elemento: 'arsenal',
      escola: 'combate_fisico',
      fontes: [fonte('mana')],
      energia: 24,
      tempoConjuracaoSegundos: 1.2,
      alcanceMetros: 0,
    }),
    promete: { arquetipos: ['espadachim_arcano'], elementos: ['encantamento', 'arsenal'] },
  },

  // ================= complexidade 2: triplas e mecânicas extras =============
  {
    id: 'vulcanologo',
    nome: 'Vulcanólogo',
    personagem: 'Ígnea, a Vulcanóloga',
    descricao: 'Faz o terreno entrar em erupção e escurece o céu. Fogo + Terra + Ar.',
    ensina: 'TRÊS elementos formam uma combinação — mais largura, não mais altura.',
    papel: 'area',
    complexidade: 2,
    elementos: { fogo: 18, terra: 18, ar: 18 },
    escolas: { conjuracao: 14 },
    recursos: { mana: 10 },
    talentos: { area_ampliada: 3, sintonia_de_receita: 2 },
    skill: sk({
      nome: 'Erupção Dirigida',
      elemento: 'vulcao',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 34,
      tempoConjuracaoSegundos: 3,
      area: circulo(9),
      capacidadeExigida: 'erupcao_dirigida',
    }),
    promete: { arquetipos: ['vulcanologo'], elementos: ['vulcao', 'lava', 'incendio'] },
  },
  {
    id: 'senhor_das_neves',
    nome: 'Senhor das Neves',
    personagem: 'Kolda, Senhora das Neves',
    descricao: 'Congela o campo e transforma o inverno em território. Água + Ar + Terra.',
    ensina: 'Combinação de 3 concede meias-identidades dos pares que contém.',
    papel: 'controle',
    complexidade: 2,
    elementos: { agua: 16, ar: 16, terra: 16 },
    escolas: { maldicao: 12, conjuracao: 6 },
    recursos: { mana: 10 },
    talentos: { area_ampliada: 3, dano_ao_longo_do_tempo: 2 },
    skill: sk({
      nome: 'Nevasca Perpétua',
      elemento: 'nevasca',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 3,
      area: circulo(10),
      entrega: continuo(16),
      capacidadeExigida: 'nevasca_perpetua',
    }),
    promete: { arquetipos: ['senhor_das_neves'], elementos: ['nevasca', 'gelo', 'pantano'] },
  },
  {
    id: 'gladiador',
    nome: 'Gladiador',
    personagem: 'Rusco, o Gladiador',
    descricao: 'Encadeia golpes onde cada eco arma o próximo. Marcial + Vigor + Som.',
    ensina: 'Som é um elemento base — ritmo e eco são mecânica, não tema.',
    papel: 'linha_de_frente',
    complexidade: 2,
    elementos: { marcial: 18, vida: 18, ar: 18, terra: 18 },
    escolas: { combate_fisico: 14 },
    recursos: { furia: 10 },
    talentos: { sequencia_marcial: 3, ritmo_de_guerra: 2 },
    skill: sk({
      nome: 'Golpe Aclamado',
      elemento: 'gladiador',
      escola: 'combate_fisico',
      fontes: [fonte('furia')],
      energia: 28,
      tempoConjuracaoSegundos: 1.2,
      alcanceMetros: 0,
      capacidadeExigida: 'golpe_aclamado',
    }),
    promete: { arquetipos: ['gladiador_arq'], elementos: ['gladiador', 'vigor', 'cadencia'] },
  },
  {
    id: 'executor',
    nome: 'Executor',
    personagem: 'Vahn, o Executor',
    descricao: 'Executa alvos enfraquecidos com um corte só. Marcial + Luz + Morte.',
    ensina: 'Elementos opostos (luz e morte) geram TENSÃO — potência com custo.',
    papel: 'foco',
    complexidade: 2,
    elementos: { marcial: 17, luz: 17, morte: 17 },
    escolas: { combate_fisico: 14 },
    recursos: { fe: 8, furia: 6 },
    talentos: { golpe_devastador: 3, endossar_elemento: 2 },
    skill: sk({
      nome: 'Corte do Veredito',
      elemento: 'lamina_do_juizo',
      escola: 'combate_fisico',
      fontes: [fonte('fe', 60), fonte('furia', 40)],
      energia: 30,
      tempoConjuracaoSegundos: 1.5,
      alcanceMetros: 0,
      capacidadeExigida: 'corte_do_veredito',
    }),
    promete: {
      arquetipos: ['executor'],
      elementos: ['lamina_do_juizo', 'lamina_radiante', 'fio_funebre'],
    },
  },
  {
    id: 'doutor_da_praga',
    nome: 'Doutor da Praga',
    personagem: 'Sr. Corvo',
    descricao: 'Espalha uma praga que salta de alvo em alvo. Morte + Vileza + Água.',
    ensina: 'Contágio faz a maldição saltar de alvo em alvo.',
    papel: 'controle',
    complexidade: 2,
    referencia: 'PoE, folclore medieval',
    elementos: { morte: 16, vileza: 16, agua: 16 },
    escolas: { maldicao: 14 },
    recursos: { mana: 10 },
    talentos: { contagio: 3, dano_ao_longo_do_tempo: 3, area_ampliada: 2 },
    skill: sk({
      nome: 'Vetor de Contágio',
      elemento: 'peste_negra',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(7),
      entrega: continuo(18),
      capacidadeExigida: 'vetor_de_contagio',
    }),
    promete: { arquetipos: ['doutor_da_praga'], elementos: ['peste_negra', 'praga', 'acido'] },
  },
  {
    id: 'taumaturgo',
    nome: 'Taumaturgo',
    personagem: 'Irmã Vesna',
    descricao: 'Desfaz ferimentos que já deveriam ser permanentes. Luz + Vida + Arcano.',
    ensina: 'Bênção com três elementos alcança o que nenhum par alcança.',
    papel: 'suporte',
    complexidade: 2,
    elementos: { luz: 16, vida: 16, arcano: 16 },
    escolas: { benca: 15 },
    recursos: { fe: 12 },
    talentos: { exaltacao: 3, vinculo_de_grupo: 3, devocao: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Milagre Menor',
      elemento: 'milagre',
      escola: 'benca',
      fontes: [fonte('fe')],
      energia: 30,
      tempoConjuracaoSegundos: 3,
      area: circulo(6),
      entrega: continuo(12),
      capacidadeExigida: 'milagre_menor',
    }),
    promete: { arquetipos: ['taumaturgo'], elementos: ['milagre', 'santidade', 'essencia'] },
  },
  {
    id: 'astrofisico',
    nome: 'Astrofísico',
    personagem: 'Doutor Kess',
    descricao: 'Detona uma estrela em cima do campo de batalha. Espaço + Fogo + Gravidade.',
    ensina: 'Gravidade e espaço abrem a metade cósmica da constelação.',
    papel: 'area',
    complexidade: 2,
    referencia: 'FF (Meteor), Destiny',
    elementos: { fogo: 17, gravidade: 17, ar: 17 },
    escolas: { conjuracao: 15 },
    recursos: { mana: 12 },
    talentos: { area_ampliada: 4, canalizacao_profunda: 3 },
    skill: sk({
      nome: 'Detonar Estrela',
      elemento: 'supernova',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 40,
      tempoConjuracaoSegundos: 4,
      area: circulo(12),
      capacidadeExigida: 'detonar_estrela',
    }),
    promete: { arquetipos: ['astrofisico'], elementos: ['supernova', 'supernova', 'fornalha_estelar'] },
  },
  {
    id: 'hipnotizador',
    nome: 'Hipnotizador',
    personagem: 'A Voz',
    descricao: 'Transforma a própria voz em ordem que o inimigo obedece. Som + Arcano + Sombra.',
    ensina: 'Controle puro — impacto baixo, efeito de campo alto.',
    papel: 'controle',
    complexidade: 3,
    elementos: { arcano: 19, sombra: 19, ar: 19, vida: 19 },
    escolas: { maldicao: 14 },
    recursos: { mana: 10, ressonancia: 8 },
    talentos: { aflicao_profunda: 3, afinacao: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Sugestão',
      elemento: 'hipnose',
      escola: 'maldicao',
      fontes: [fonte('mana', 60), fonte('ressonancia', 40)],
      energia: 26,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
      entrega: continuo(10),
      capacidadeExigida: 'sugestao',
    }),
    promete: { arquetipos: ['hipnotizador'], elementos: ['hipnose', 'sussurro', 'ocultismo'] },
  },
  {
    id: 'vidente',
    nome: 'Vidente',
    personagem: 'Olho-de-Amanhã',
    descricao: 'Vê o golpe antes de ele partir e desvia o grupo. Tempo + Sombra + Espaço.',
    ensina: 'Presságio existe só como tripla — nenhum par chega lá.',
    papel: 'suporte',
    complexidade: 2,
    elementos: { sombra: 19, gravidade: 19, arcano: 19, ar: 19 },
    escolas: { benca: 12, maldicao: 6 },
    recursos: { mana: 10 },
    talentos: { persistencia: 3, leitor_de_constelacao: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Esquiva Profética',
      elemento: 'presagio',
      escola: 'benca',
      fontes: [fonte('mana')],
      energia: 24,
      tempoConjuracaoSegundos: 2,
      area: circulo(5),
      entrega: continuo(14),
      capacidadeExigida: 'esquiva_profetica',
    }),
    promete: { arquetipos: ['vidente'], elementos: ['presagio', 'materia_escura', 'horizonte_de_eventos'] },
  },
  {
    id: 'cronomante',
    nome: 'Cronomante',
    personagem: 'Aeon, o Cronomante',
    descricao: 'Acelera aliados, atrasa inimigos e para o tempo. Tempo + Arcano.',
    ensina: 'Uma classe pode gastar em três escolas em vez de aprofundar uma.',
    papel: 'controle',
    complexidade: 2,
    referencia: 'ToS, FF',
    elementos: { arcano: 16, gravidade: 16 },
    escolas: { conjuracao: 12, benca: 10, maldicao: 8 },
    recursos: { mana: 10 },
    talentos: { area_ampliada: 2, metamagia_gemea: 2 },
    skill: sk({
      nome: 'Parada Temporal',
      elemento: 'tempo',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      area: circulo(5),
    }),
    promete: { arquetipos: ['cronomante'], elementos: ['tempo'] },
  },
  {
    id: 'senhor_da_gravidade',
    nome: 'Senhor da Gravidade',
    personagem: 'Vahl, o Peso',
    descricao: 'Esmaga um alvo sob o peso do próprio mundo. Gravidade + Terra + Arcano.',
    ensina: 'Impacto concentrado num alvo só rende mais que espalhado.',
    papel: 'foco',
    complexidade: 2,
    referencia: 'FF (Demi)',
    elementos: { gravidade: 16, terra: 12, arcano: 12 },
    escolas: { conjuracao: 14 },
    recursos: { mana: 10 },
    talentos: { impacto_imediato: 3, perfuracao: 2 },
    skill: sk({
      nome: 'Demi',
      elemento: 'gravidade',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 2.2,
      capacidadeExigida: 'demi',
    }),
    promete: { arquetipos: ['senhor_da_gravidade'], elementos: ['colapso', 'tempo'] },
  },
  {
    id: 'cavaleiro_dragao',
    nome: 'Cavaleiro Dragão',
    personagem: 'Kain, o Cavaleiro Dragão',
    descricao: 'Cai do céu de lança em punho, montado num wyvern. Marcial + Ar + Fogo.',
    ensina: 'Bestiário: capturar, domar e usar a criatura como montaria.',
    papel: 'foco',
    complexidade: 2,
    referencia: 'FF (Dragoon)',
    elementos: { marcial: 14, ar: 14, fogo: 10 },
    escolas: { combate_fisico: 14, evocacao: 10 },
    recursos: { furia: 8 },
    talentos: { salto: 3, instinto_de_caca: 2, vinculo_primal: 1, montaria: 1 },
    bestiario: [{ criaturaId: 'wyvern', vinculo: 1 }],
    skill: sk({
      nome: 'Salto Dracônico',
      elemento: 'esgrima',
      escola: 'combate_fisico',
      fontes: [fonte('furia')],
      energia: 28,
      tempoConjuracaoSegundos: 1.5,
      alcanceMetros: 0,
      montariaId: 'wyvern',
    }),
    promete: { arquetipos: ['cavaleiro_dragao'], elementos: ['esgrima', 'forja'] },
  },
  {
    id: 'senhor_das_feras',
    nome: 'Senhor das Feras',
    personagem: 'Ysra, a Domadora',
    descricao: 'Caça, doma e leva a matilha para a briga. Vigor + Vida.',
    ensina: 'Doma: vínculo com várias criaturas, limitado por talento.',
    papel: 'invocador',
    complexidade: 2,
    referencia: 'WoW, Ragnarok',
    elementos: { vida: 14, terra: 8, marcial: 14 },
    escolas: { evocacao: 14, combate_fisico: 8 },
    recursos: { mana: 8, furia: 6 },
    talentos: {
      vinculo_primal: 1,
      matilha_domada: 3,
      instinto_de_caca: 3,
      guarda_da_fera: 2,
    },
    bestiario: [
      { criaturaId: 'lobo', vinculo: 2 },
      { criaturaId: 'urso', vinculo: 1 },
      { criaturaId: 'falcao', vinculo: 1 },
    ],
    skill: sk({
      nome: 'Chamado da Matilha',
      elemento: 'vigor',
      escola: 'evocacao',
      fontes: [fonte('mana', 60), fonte('furia', 40)],
      energia: 30,
      tempoConjuracaoSegundos: 2.5,
      capacidadeExigida: 'evocar_feras',
      evocacao: { modo: 'capturada', criaturaId: 'lobo' },
    }),
    promete: { arquetipos: ['senhor_das_feras'], elementos: ['vigor', 'flora'] },
  },
  {
    id: 'mestre_de_armas',
    nome: 'Mestre de Armas',
    personagem: 'Cem-Lâminas',
    descricao: 'Troca a própria alma por golpes que não erram. Marcial + Vigor.',
    ensina: 'Duas fontes de energia numa skill só, em proporções livres.',
    papel: 'foco',
    complexidade: 2,
    elementos: { marcial: 14, vida: 10 },
    escolas: { combate_fisico: 12 },
    recursos: { soullink: 8, furia: 6 },
    talentos: { sequencia_marcial: 2, elo_profundo: 2 },
    skill: sk({
      nome: 'Dança de Mil Cortes',
      elemento: 'vigor',
      escola: 'combate_fisico',
      fontes: [fonte('soullink', 60), fonte('furia', 40)],
      energia: 25,
      tempoConjuracaoSegundos: 1.5,
      alcanceMetros: 0,
    }),
    promete: { arquetipos: ['mestre_de_armas'], elementos: ['vigor'] },
  },
  {
    id: 'arsenal',
    nome: 'Arsenal Espectral',
    personagem: 'Kael, Arsenal Espectral',
    descricao: 'Solta um enxame de armas que luta sozinho. Vigor + Arcano.',
    ensina: 'Evocação + combate físico: a escola dupla abre arquétipos próprios.',
    papel: 'invocador',
    complexidade: 2,
    elementos: { arcano: 15, vida: 15, marcial: 15 },
    escolas: { evocacao: 13, combate_fisico: 13 },
    recursos: { furia: 9 },
    talentos: { colosso: 2, vinculo_marcial: 2 },
    skill: sk({
      nome: 'Armas Dançantes',
      elemento: 'vigor',
      escola: 'evocacao',
      fontes: [fonte('furia')],
      energia: 35,
      tempoConjuracaoSegundos: 2,
      alcanceMetros: 0,
      capacidadeExigida: 'evocar_armas_autonomas',
    }),
    promete: { arquetipos: ['arsenal_espectral'], elementos: ['encantamento'] },
  },
  {
    id: 'bokor',
    nome: 'Bokor',
    personagem: 'Mama Ndeye',
    descricao: 'Levanta servos de vodu que apanham no seu lugar. Morte + Vileza + Sombra.',
    ensina: 'Maldição pode invocar: escola não amarra o tipo de efeito.',
    papel: 'invocador',
    complexidade: 2,
    referencia: 'Tree of Savior',
    elementos: { morte: 16, vileza: 14, sombra: 10 },
    escolas: { maldicao: 14, evocacao: 8 },
    recursos: { mana: 10 },
    talentos: { enxame: 3, contagio: 2 },
    skill: sk({
      nome: 'Zumbi Servo',
      elemento: 'praga',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      capacidadeExigida: 'zumbi_servo',
    }),
    promete: { arquetipos: ['bokor'], elementos: ['praga', 'terror', 'espectro'] },
  },
  {
    id: 'menestrel',
    nome: 'Menestrel',
    personagem: 'Lira de Prata',
    descricao: 'Rege canções que reforçam o grupo enquanto tocam. Som + Luz + Ar.',
    ensina: 'Ressonância: recurso que sobe a cada repetição e depois zera.',
    papel: 'suporte',
    complexidade: 2,
    referencia: 'Ragnarok (Bard), D&D',
    elementos: { luz: 15, ar: 16, vida: 16 },
    escolas: { benca: 14 },
    recursos: { ressonancia: 12, mana: 6 },
    talentos: { cancao_persistente: 3, afinacao: 3, area_ampliada: 2 },
    skill: sk({
      nome: 'Reger Sinfonia',
      elemento: 'harmonia',
      escola: 'benca',
      fontes: [fonte('ressonancia', 70), fonte('mana', 30)],
      energia: 24,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(8),
      entrega: continuo(16),
      capacidadeExigida: 'reger_sinfonia',
    }),
    promete: { arquetipos: ['menestrel'], elementos: ['harmonia', 'som'] },
  },
  {
    id: 'astromante',
    nome: 'Astromante',
    personagem: 'Nyx da Constelação',
    descricao: 'Chama meteoros e abre portais. Espaço + Arcano + Luz.',
    ensina: 'Espaço é o elemento mais versátil da borda da constelação.',
    papel: 'area',
    complexidade: 2,
    referencia: 'ToS (Sage), FF',
    elementos: { arcano: 12, luz: 15, gravidade: 16, ar: 16 },
    escolas: { conjuracao: 14 },
    recursos: { mana: 12 },
    talentos: { area_ampliada: 4, eco_arcano: 2 },
    skill: sk({
      nome: 'Chuva de Meteoros',
      elemento: 'espaco',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 34,
      tempoConjuracaoSegundos: 3.5,
      area: circulo(11),
      capacidadeExigida: 'chuva_de_meteoros',
    }),
    promete: { arquetipos: ['astromante'], elementos: ['continuum', 'constelacao'] },
  },

  // ============ complexidade 3: quádruplas, fusão e modificadores ==========
  {
    id: 'senhor_do_clima',
    nome: 'Senhor do Clima',
    personagem: 'Almirante Vento',
    descricao: 'Cerca o campo com uma frente de tempestade. Quatro elementos de clima.',
    ensina: 'QUATRO elementos numa combinação — o topo da largura de identidade.',
    papel: 'area',
    complexidade: 3,
    elementos: { agua: 21, ar: 21, eletricidade: 21, vida: 21 },
    escolas: { conjuracao: 15 },
    recursos: { mana: 12 },
    talentos: { area_ampliada: 5, sintonia_de_receita: 3, convergencia_elemental: 2 },
    skill: sk({
      nome: 'Frente de Tempestade',
      elemento: 'tempestade_perfeita',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 42,
      tempoConjuracaoSegundos: 4,
      area: circulo(14),
      capacidadeExigida: 'frente_de_tempestade',
    }),
    promete: {
      arquetipos: ['senhor_do_clima'],
      elementos: ['tempestade_perfeita', 'furacao', 'tempestade'],
    },
  },
  {
    id: 'elementalista_pleno',
    nome: 'Elementalista Pleno',
    personagem: 'O Quarteto',
    descricao: 'Assume os quatro elementos clássicos e troca entre eles. Fogo + Água + Terra + Ar.',
    ensina: 'Os quatro clássicos juntos: a quádrupla mais familiar que existe.',
    papel: 'area',
    complexidade: 3,
    referencia: 'Avatar, D&D',
    elementos: { fogo: 21, agua: 21, terra: 21, ar: 21 },
    escolas: { conjuracao: 14, benca: 6 },
    recursos: { mana: 12 },
    talentos: { convergencia_elemental: 3, sintonia_de_receita: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Forma Elemental',
      elemento: 'avatar_elemental',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 38,
      tempoConjuracaoSegundos: 3,
      area: circulo(6),
      entrega: continuo(20),
      capacidadeExigida: 'forma_elemental',
    }),
    promete: {
      arquetipos: ['elementalista_pleno'],
      elementos: ['avatar_elemental', 'vulcao', 'nevasca', 'lava', 'gelo'],
    },
  },
  {
    id: 'cavaleiro_absoluto',
    nome: 'Cavaleiro Absoluto',
    personagem: 'O Invicto',
    descricao: 'Acerta todo golpe e apara o que não deveria dar para aparar. Quatro elementos marciais.',
    ensina: 'Uma quádrupla marcial rivaliza com magia na mesma escala de pontos.',
    papel: 'linha_de_frente',
    complexidade: 3,
    elementos: { marcial: 20, luz: 20, vida: 20, gravidade: 20, arcano: 20 },
    escolas: { combate_fisico: 15 },
    recursos: { furia: 10, fe: 8 },
    talentos: { sequencia_marcial: 3, postura_inabalavel: 3, ritmo_de_guerra: 3 },
    skill: sk({
      nome: 'Técnica Perfeita',
      elemento: 'cavaleiro_absoluto',
      escola: 'combate_fisico',
      fontes: [fonte('furia', 60), fonte('fe', 40)],
      energia: 36,
      tempoConjuracaoSegundos: 1.6,
      alcanceMetros: 0,
      capacidadeExigida: 'tecnica_perfeita',
    }),
    promete: {
      arquetipos: ['cavaleiro_absoluto_arq'],
      elementos: ['cavaleiro_absoluto', 'bravura', 'vigor'],
    },
  },
  {
    id: 'portador_do_ragnarok',
    nome: 'Portador do Ragnarök',
    personagem: 'O Crepúsculo',
    descricao: 'Anuncia o fim e cumpre na hora marcada. Fogo + Morte + Gravidade + Tempo.',
    ensina: 'Combinações com muita tensão pagam caro e entregam mais.',
    papel: 'area',
    complexidade: 3,
    referencia: 'Ragnarok Online, mitologia nórdica',
    elementos: { fogo: 21, morte: 21, gravidade: 21, arcano: 21 },
    escolas: { conjuracao: 15 },
    recursos: { mana: 14 },
    talentos: { canalizacao_profunda: 3, maestria_paradoxal: 3, area_ampliada: 5 },
    skill: sk({
      nome: 'Crepúsculo',
      elemento: 'ragnarok',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 46,
      tempoConjuracaoSegundos: 5,
      area: circulo(13),
      capacidadeExigida: 'crepusculo',
    }),
    promete: {
      arquetipos: ['portador_do_ragnarok'],
      elementos: ['ragnarok', 'paradoxo', 'implosao'],
    },
  },
  {
    id: 'semeador',
    nome: 'Semeador',
    personagem: 'O Primeiro Dia',
    descricao: 'Refaz o terreno e o grupo por onde passa. Vida + Luz + Terra + Água.',
    ensina: 'Suporte na escala máxima — cura que refaz o terreno junto.',
    papel: 'suporte',
    complexidade: 3,
    elementos: { vida: 20, luz: 20, terra: 20, agua: 20 },
    escolas: { benca: 15 },
    recursos: { fe: 14 },
    talentos: { exaltacao: 3, vinculo_de_grupo: 3, devocao: 3, area_ampliada: 4 },
    skill: sk({
      nome: 'Primeiro Dia',
      elemento: 'genesis',
      escola: 'benca',
      fontes: [fonte('fe')],
      energia: 38,
      tempoConjuracaoSegundos: 4,
      area: circulo(12),
      entrega: continuo(20),
      capacidadeExigida: 'primeiro_dia',
    }),
    promete: {
      arquetipos: ['semeador'],
      elementos: ['genesis', 'selva', 'santidade', 'flora'],
    },
  },
  {
    id: 'regente_do_caos',
    nome: 'Regente do Caos',
    personagem: 'O Maestro',
    descricao: 'Desmonta o inimigo acorde por acorde. Som + Vileza + Sombra + Arcano.',
    ensina: 'Controle de quádrupla — desfaz o inimigo em vez de matá-lo.',
    papel: 'controle',
    complexidade: 3,
    elementos: { vileza: 21, sombra: 21, arcano: 21, ar: 21, vida: 21 },
    escolas: { maldicao: 15 },
    recursos: { mana: 12, ressonancia: 10 },
    talentos: { aflicao_profunda: 3, afinacao: 3, area_ampliada: 3 },
    skill: sk({
      nome: 'Reger o Caos',
      elemento: 'sinfonia_do_caos',
      escola: 'maldicao',
      fontes: [fonte('mana', 60), fonte('ressonancia', 40)],
      energia: 36,
      tempoConjuracaoSegundos: 3.5,
      area: circulo(10),
      entrega: continuo(16),
      capacidadeExigida: 'reger_o_caos',
    }),
    promete: {
      arquetipos: ['regente_do_caos'],
      elementos: ['sinfonia_do_caos', 'delirio', 'dissonancia', 'sabbat'],
    },
  },
  {
    id: 'arquiteto_da_realidade',
    nome: 'Arquiteto da Realidade',
    personagem: 'O Compasso',
    descricao: 'Reescreve as regras locais da física. Arcano + Espaço + Tempo + Gravidade.',
    ensina: 'A quádrupla mais cara do sistema, e o que ela custa em foco.',
    papel: 'controle',
    complexidade: 3,
    elementos: { arcano: 22, gravidade: 22, ar: 22, terra: 20, fogo: 15, luz: 15 },
    escolas: { conjuracao: 15 },
    recursos: { mana: 14 },
    talentos: { maestria_paradoxal: 3, leitor_de_constelacao: 3, area_ampliada: 3 },
    skill: sk({
      nome: 'Reescrever Local',
      elemento: 'arquiteto_da_realidade',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 40,
      tempoConjuracaoSegundos: 4.5,
      area: circulo(9),
      entrega: continuo(14),
      capacidadeExigida: 'reescrever_local',
    }),
    promete: {
      arquetipos: ['demiurgo_absoluto'],
      elementos: ['arquiteto_da_realidade', 'big_bang', 'continuum', 'espaco'],
    },
  },
  {
    id: 'portador_do_nulo',
    nome: 'Portador do Nulo',
    personagem: 'O Sem-Nome',
    descricao: 'Sabe um pouco de tudo e por isso anula qualquer coisa. Os 13 elementos.',
    ensina: 'A receita mais larga do sistema — largura pura, zero profundidade.',
    papel: 'controle',
    complexidade: 3,
    elementos: {
      fogo: 8, agua: 8, terra: 8, ar: 8, eletricidade: 8, arcano: 8,
      sombra: 8, luz: 8, vileza: 8, morte: 8, vida: 8, marcial: 8,
      gravidade: 8,
    },
    escolas: { conjuracao: 10 },
    recursos: { mana: 10 },
    skill: sk({
      nome: 'Anulação',
      elemento: 'nulo',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 2,
      capacidadeExigida: 'anular_magia',
    }),
    promete: { arquetipos: ['portador_do_nulo'], elementos: ['nulo'] },
  },

  // --------------------------- presets de fusão ----------------------------
  {
    id: 'fusionista',
    nome: 'Fusionista',
    personagem: 'Ord, o Fusionista',
    descricao: 'Lança duas skills como uma só, mais forte que a soma. Água + Morte + Sombra + Vileza.',
    ensina: 'FUSÃO de 2ª geração: o elemento resultante é a soma das receitas.',
    papel: 'area',
    complexidade: 3,
    // 20 em cada base: com menos, a quádrupla não fecha e a fusão CAI para um
    // par, avisando que perdeu a convergência. Um preset que existe para
    // ensinar fusão não pode ensinar o caso degradado.
    //
    // A receita saiu dos quatro clássicos porque ali ele era um CLONE do
    // Elementalista Pleno — mesma distribuição e o mesmo arquétipo prometido.
    // O Fusionista existe para ensinar a mecânica, não para repetir a ficha.
    elementos: { agua: 20, morte: 20, sombra: 20, vileza: 20 },
    escolas: { conjuracao: 15, maldicao: 8 },
    recursos: { mana: 12 },
    talentos: { arte_da_fusao: 3, estabilizador: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Névoa Corrosiva',
      elemento: 'veneno',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
    }),
    fusao: {
      nome: 'Abismo da Praga',
      componentes: [
        sk({
          nome: 'Névoa Corrosiva',
          elemento: 'veneno',
          escola: 'maldicao',
          fontes: [fonte('mana')],
          energia: 26,
          tempoConjuracaoSegundos: 2.5,
          area: circulo(6),
        }),
        sk({
          nome: 'Manto de Terror',
          elemento: 'terror',
          escola: 'maldicao',
          fontes: [fonte('mana')],
          energia: 24,
          tempoConjuracaoSegundos: 2,
          area: circulo(5),
        }),
      ],
    },
    promete: {
      arquetipos: [],
      elementos: ['veneno', 'terror', 'praga', 'abismo'],
    },
  },
  {
    id: 'catalisador',
    nome: 'Catalisador',
    personagem: 'Ryn, a Catalisadora',
    descricao: 'Funde três skills de uma vez e paga o preço disso. Fogo + Terra + Morte + Sombra.',
    ensina: 'Fusão de 3ª geração e o teto de eficiência que a impede de dominar.',
    papel: 'area',
    complexidade: 3,
    elementos: { fogo: 18, terra: 18, morte: 18, sombra: 18 },
    escolas: { conjuracao: 15, maldicao: 8 },
    recursos: { mana: 14 },
    talentos: { arte_da_fusao: 3, catalisador: 3, area_ampliada: 1 },
    skill: sk({
      nome: 'Erupção',
      elemento: 'lava',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
    }),
    fusao: {
      nome: 'Cadinho do Fim',
      componentes: [
        sk({
          nome: 'Erupção',
          elemento: 'lava',
          escola: 'conjuracao',
          fontes: [fonte('mana')],
          energia: 26,
          tempoConjuracaoSegundos: 2.5,
          area: circulo(6),
        }),
        sk({
          nome: 'Manto Espectral',
          elemento: 'espectro',
          escola: 'maldicao',
          fontes: [fonte('mana')],
          energia: 22,
          tempoConjuracaoSegundos: 2,
          area: circulo(5),
        }),
        sk({
          nome: 'Cinza Negra',
          elemento: 'fogo_negro',
          escola: 'conjuracao',
          fontes: [fonte('mana')],
          energia: 24,
          tempoConjuracaoSegundos: 2,
          area: circulo(5),
        }),
      ],
      escolaDominante: 'conjuracao',
    },
    promete: { arquetipos: [], elementos: ['lava', 'espectro', 'fogo_negro'] },
  },

  // ----------------------- presets de modificadores ------------------------
  {
    id: 'engenheiro_de_skill',
    nome: 'Engenheiro de Skill',
    personagem: 'Tavro, o Engenheiro',
    descricao: 'Refaz um dardo simples com quatro modificadores encadeados. Fogo + Arcano.',
    ensina: 'MODIFICADORES: cada um multiplica o custo e exige tags compatíveis.',
    papel: 'foco',
    complexidade: 3,
    referencia: 'PoE (support gems)',
    elementos: { fogo: 20, arcano: 16 },
    escolas: { conjuracao: 16 },
    recursos: { mana: 14 },
    talentos: { engenho_de_skill: 3, economia_de_recurso: 3, fluxo_constante: 2 },
    skill: sk({
      nome: 'Dardo Refeito',
      elemento: 'fogo_feiticeiro',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 1.8,
      area: circulo(4),
      modificadores: [
        'projeteis_multiplos',
        'penetracao_encadeada',
        'concentracao',
        'contencao_disciplinada',
      ],
    }),
    promete: { arquetipos: [], elementos: ['fogo_feiticeiro'] },
  },
  {
    id: 'sobrecarregado',
    nome: 'Sobrecarregado',
    personagem: 'Vesk, a Sobrecarregada',
    descricao: 'Troca segurança por potência bruta e paga caro. Eletricidade + Arcano + Vigor.',
    ensina: 'Modificadores negativos existem: alguns compram poder com risco.',
    papel: 'foco',
    complexidade: 3,
    elementos: { eletricidade: 20, arcano: 18, vida: 16, marcial: 16 },
    escolas: { conjuracao: 15 },
    recursos: { mana: 12, soullink: 8 },
    talentos: { engenho_de_skill: 2, pacto_de_sangue: 2, elo_profundo: 2 },
    skill: sk({
      nome: 'Descarga Sobrecarregada',
      elemento: 'sobrecarga',
      escola: 'conjuracao',
      fontes: [fonte('mana', 70), fonte('soullink', 30)],
      energia: 34,
      tempoConjuracaoSegundos: 2.2,
      modificadores: ['sobrecarga_bruta', 'canalizacao_arriscada', 'sangria_arcana'],
    }),
    promete: { arquetipos: [], elementos: ['sobrecarga', 'fluxo', 'reflexo'] },
  },

  // ----------------------------- ofícios -----------------------------------
  {
    id: 'mestre_encantador',
    nome: 'Mestre Encantador',
    personagem: 'Perim, o Encantador',
    descricao: 'Grava elementos inteiros em objetos prontos. Arcano + Luz + Terra.',
    ensina: 'PROFISSÕES são um eixo próprio de pontos, fora da constelação.',
    papel: 'oficio',
    complexidade: 2,
    elementos: { arcano: 18, luz: 12, terra: 10 },
    escolas: { benca: 12, conjuracao: 8 },
    recursos: { mana: 10 },
    talentos: { mao_de_mestre: 3, olho_de_materiais: 2, assinatura_do_artesao: 1 },
    profissoes: { encantador: 12, joalheiro: 8, escriba: 6 },
    skill: sk({
      nome: 'Gravar Elemento',
      elemento: 'runa',
      escola: 'benca',
      fontes: [fonte('mana')],
      energia: 22,
      tempoConjuracaoSegundos: 3,
      entrega: continuo(20),
      capacidadeExigida: 'gravar_elemento',
    }),
    promete: { arquetipos: ['mestre_encantador'], elementos: ['runa', 'cristal'] },
  },
  {
    id: 'forjador_de_guerra',
    nome: 'Forjador de Guerra',
    personagem: 'Bruna Martelo',
    descricao: 'Forja e evoca armas ainda incandescentes. Marcial + Fogo + Terra.',
    ensina: 'Ofício e combate no mesmo personagem: forja o que evoca.',
    papel: 'oficio',
    complexidade: 2,
    elementos: { marcial: 16, fogo: 16, terra: 12 },
    escolas: { evocacao: 12, combate_fisico: 10 },
    recursos: { furia: 8, mana: 6 },
    talentos: { mao_de_mestre: 3, linha_de_producao: 2, vinculo_marcial: 2 },
    profissoes: { ferreiro: 14, joalheiro: 6, curtidor: 4 },
    skill: sk({
      nome: 'Armas Flamejantes',
      elemento: 'forja',
      escola: 'evocacao',
      fontes: [fonte('furia', 60), fonte('mana', 40)],
      energia: 28,
      tempoConjuracaoSegundos: 2,
      capacidadeExigida: 'evocar_armas_flamejantes',
    }),
    promete: { arquetipos: ['forjador_de_guerra'], elementos: ['forja', 'aco', 'lava'] },
  },
  {
    id: 'luthier_de_guerra',
    nome: 'Luthier de Guerra',
    personagem: 'Céu de Cordas',
    descricao: 'Constrói o instrumento e a canção que ele toca. Som + Marcial + Luz.',
    ensina: 'Um ofício pode ser a identidade inteira de uma classe.',
    papel: 'oficio',
    complexidade: 2,
    elementos: { marcial: 15, luz: 15, ar: 16, vida: 16 },
    escolas: { benca: 12, combate_fisico: 8 },
    recursos: { ressonancia: 10, mana: 6 },
    talentos: { afinacao: 3, cancao_persistente: 2, area_ampliada: 2 },
    profissoes: { luthier: 14, tecelao: 6, artesao: 6 },
    skill: sk({
      nome: 'Marcha de Guerra',
      elemento: 'cadencia',
      escola: 'benca',
      fontes: [fonte('ressonancia', 70), fonte('mana', 30)],
      energia: 24,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(8),
      entrega: continuo(16),
      capacidadeExigida: 'marcha_de_guerra',
    }),
    promete: { arquetipos: ['luthier_de_guerra'], elementos: ['cadencia', 'harmonia'] },
  },

  // ============ lacunas canônicas: as classes que o público procura =========
  {
    id: 'criomante',
    nome: 'Criomante',
    personagem: 'Sifra, a Criomante',
    descricao: 'Prende o inimigo no gelo antes de matar. Água + Ar.',
    ensina: 'Nem toda classe de dano quer dano: gelo compra tempo.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'Diablo, FF, Ragnarok',
    elementos: { agua: 14, ar: 14 },
    escolas: { conjuracao: 13 },
    recursos: { mana: 10 },
    talentos: { area_ampliada: 2, impacto_imediato: 2 },
    skill: sk({
      nome: 'Prisão de Gelo',
      elemento: 'gelo',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      area: circulo(7),
      capacidadeExigida: 'prisao_de_gelo',
    }),
    promete: { arquetipos: ['criomante'], elementos: ['gelo'] },
  },
  {
    id: 'monge',
    nome: 'Monge',
    personagem: 'Irmão Tuan',
    descricao: 'Luta sem arma, encadeando golpes no ritmo. Marcial + Vigor.',
    ensina: 'Ressonância cresce a cada repetição e zera se você parar.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'D&D, FF, WoW',
    elementos: { marcial: 14, vida: 14 },
    escolas: { combate_fisico: 13 },
    recursos: { ressonancia: 12 },
    talentos: { sequencia_marcial: 3, afinacao: 3, ritmo_de_guerra: 2 },
    skill: sk({
      nome: 'Punho Interior',
      elemento: 'vigor',
      escola: 'combate_fisico',
      fontes: [fonte('ressonancia')],
      energia: 24,
      tempoConjuracaoSegundos: 0.9,
      alcanceMetros: 0,
      capacidadeExigida: 'punho_interior',
    }),
    promete: { arquetipos: ['monge'], elementos: ['vigor'] },
  },
  {
    id: 'guardiao_de_aco',
    nome: 'Guardião de Aço',
    personagem: 'Bór, o Muro',
    descricao: 'Segura a linha sem pedir bênção a ninguém. Terra + Vigor.',
    ensina: 'Dá para ser muro sem ser sagrado — tanque secular.',
    papel: 'linha_de_frente',
    complexidade: 1,
    referencia: 'WoW (Protection), GW2',
    elementos: { terra: 15, vida: 15, marcial: 15 },
    escolas: { combate_fisico: 14 },
    recursos: { furia: 10 },
    talentos: { postura_inabalavel: 3, sede_de_batalha: 2, golpe_devastador: 2 },
    skill: sk({
      nome: 'Muralha Viva',
      elemento: 'tita',
      escola: 'combate_fisico',
      fontes: [fonte('furia')],
      energia: 26,
      tempoConjuracaoSegundos: 1.5,
      alcanceMetros: 0,
      area: circulo(4),
      entrega: continuo(12),
      capacidadeExigida: 'muralha_viva',
    }),
    promete: { arquetipos: ['guardiao_de_aco'], elementos: ['tita'] },
  },
  {
    id: 'patrulheiro',
    nome: 'Patrulheiro',
    personagem: 'Enna do Vale',
    descricao: 'Atira de longe com um animal caçando junto. Vigor + Vida.',
    ensina: 'Longo Alcance e Evocação na mesma ficha: arqueiro com companheiro.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'D&D (Ranger), WoW (Hunter)',
    elementos: { vida: 13, ar: 8, marcial: 13 },
    escolas: { longo_alcance: 13, evocacao: 9 },
    recursos: { mana: 8 },
    talentos: { olho_de_aguia: 3, vinculo_primal: 1, alcance_estendido: 2 },
    bestiario: [{ criaturaId: 'falcao', vinculo: 2 }],
    skill: sk({
      nome: 'Tiro Certeiro',
      elemento: 'vigor',
      escola: 'longo_alcance',
      fontes: [fonte('mana')],
      energia: 24,
      tempoConjuracaoSegundos: 1.6,
      alcanceMetros: 30,
      capacidadeExigida: 'tiro_certeiro',
    }),
    promete: { arquetipos: ['patrulheiro'], elementos: ['vigor'] },
  },
  {
    id: 'sombra_ambulante',
    nome: 'Sombra Ambulante',
    personagem: 'Ninguém',
    descricao: 'Aparece uma vez, mata, e some. Sombra + Vigor.',
    ensina: 'Impacto Imediato concentra todo o orçamento num golpe só.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'D&D, PoE, Ragnarok',
    elementos: { sombra: 15, vida: 15, marcial: 15 },
    escolas: { combate_fisico: 13 },
    recursos: { furia: 8, soullink: 6 },
    talentos: { impacto_imediato: 3, golpe_devastador: 3, elo_profundo: 2 },
    skill: sk({
      nome: 'Execução Furtiva',
      elemento: 'assassinio',
      escola: 'combate_fisico',
      fontes: [fonte('furia', 60), fonte('soullink', 40)],
      energia: 28,
      tempoConjuracaoSegundos: 1,
      alcanceMetros: 0,
      capacidadeExigida: 'execucao_furtiva',
    }),
    promete: { arquetipos: ['sombra_ambulante'], elementos: ['assassinio'] },
  },
  {
    id: 'cavaleiro_da_morte',
    nome: 'Cavaleiro da Morte',
    personagem: 'Sir Hollow',
    descricao: 'Colhe almas a cada golpe. Morte + Vigor.',
    ensina: 'Ceifa transforma combate físico em recurso.',
    papel: 'linha_de_frente',
    complexidade: 1,
    referencia: 'WoW, Diablo',
    elementos: { morte: 15, vida: 15, marcial: 15 },
    escolas: { combate_fisico: 13 },
    recursos: { soullink: 10, furia: 6 },
    talentos: { golpe_devastador: 3, pacto_de_sangue: 2, elo_profundo: 2 },
    skill: sk({
      nome: 'Golpe Ceifador',
      elemento: 'ceifa',
      escola: 'combate_fisico',
      fontes: [fonte('soullink', 60), fonte('furia', 40)],
      energia: 28,
      tempoConjuracaoSegundos: 1.4,
      alcanceMetros: 0,
      capacidadeExigida: 'golpe_ceifador',
    }),
    promete: { arquetipos: ['cavaleiro_da_morte'], elementos: ['ceifa'] },
  },
  {
    id: 'demonologista',
    nome: 'Demonologista',
    personagem: 'A Signatária',
    descricao: 'Assina pactos e cobra a dívida em demônios. Vileza + Arcano.',
    ensina: 'Evocação de escola pura: o arquétipo vem do recurso, não do elemento.',
    papel: 'invocador',
    complexidade: 1,
    referencia: 'D&D (Warlock), PoE',
    elementos: { vileza: 15, arcano: 15 },
    escolas: { evocacao: 13, maldicao: 8 },
    recursos: { mana: 10 },
    talentos: { colosso: 3, simbiose: 2 },
    skill: sk({
      nome: 'Chamado do Pacto',
      elemento: 'pacto',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 3,
      capacidadeExigida: 'evocar_demonios',
    }),
    promete: { arquetipos: ['demonologista'], elementos: ['pacto'] },
  },
  {
    id: 'verdejante',
    nome: 'Verdejante',
    personagem: 'Raiz-Antiga',
    descricao: 'Faz o mato brotar e lutar por você. Vida + Terra.',
    ensina: 'Invocação que também é terreno: a planta fica onde nasceu.',
    papel: 'invocador',
    complexidade: 1,
    referencia: 'D&D (Druida), WoW',
    elementos: { vida: 15, terra: 15 },
    escolas: { evocacao: 13, benca: 8 },
    recursos: { mana: 10 },
    talentos: { enxame: 3, persistencia: 2, guarda_da_fera: 2 },
    skill: sk({
      nome: 'Vinhas Guardiãs',
      elemento: 'flora',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      capacidadeExigida: 'evocar_plantas',
    }),
    promete: { arquetipos: ['verdejante'], elementos: ['flora'] },
  },
  {
    id: 'vampiro_espiritual',
    nome: 'Vampiro Espiritual',
    personagem: 'Condessa Ílis',
    descricao: 'Drena vida à distância e devolve em si mesma. Sombra + Vida.',
    ensina: 'Maldição que cura: o mesmo efeito nos dois sentidos.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'ToS, Diablo',
    elementos: { sombra: 15, vida: 15 },
    escolas: { maldicao: 13 },
    recursos: { soullink: 12 },
    talentos: { aflicao_profunda: 3, elo_profundo: 3, dano_ao_longo_do_tempo: 2 },
    skill: sk({
      nome: 'Dreno Vital',
      elemento: 'parasita',
      escola: 'maldicao',
      fontes: [fonte('soullink')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      entrega: continuo(12),
      capacidadeExigida: 'dreno_vital',
    }),
    promete: { arquetipos: ['vampiro_espiritual'], elementos: ['parasita'] },
  },
  {
    id: 'geomante',
    nome: 'Geomante',
    personagem: 'Kesh do Barro',
    descricao: 'Molda o terreno e usa o chão como arma. Terra + Conjuração.',
    ensina: 'Uma escola profunda vale tanto quanto um elemento raro.',
    papel: 'area',
    complexidade: 1,
    referencia: 'FF, D&D',
    elementos: { terra: 16, vida: 15, marcial: 15 },
    escolas: { conjuracao: 14 },
    recursos: { mana: 10 },
    talentos: { area_ampliada: 3, impacto_imediato: 2 },
    skill: sk({
      nome: 'Moldar Terreno',
      elemento: 'terra',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(9),
      capacidadeExigida: 'moldar_terreno',
    }),
    promete: { arquetipos: ['geomante'], elementos: ['tita'] },
  },
  {
    id: 'arquimago',
    nome: 'Arquimago',
    personagem: 'Mestre Oren',
    descricao: 'Sabe as três magias e reescreve as regras delas. Arcano puro.',
    ensina: 'Profundidade num elemento só, espalhada por três escolas.',
    papel: 'controle',
    complexidade: 2,
    referencia: 'D&D, FF',
    elementos: { arcano: 20, luz: 10 },
    escolas: { conjuracao: 12, evocacao: 10, benca: 10 },
    recursos: { mana: 14 },
    talentos: { metamagia_gemea: 3, eco_arcano: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Metamagia',
      elemento: 'runa',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 32,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
      capacidadeExigida: 'metamagia',
    }),
    promete: { arquetipos: ['arquimago', 'mestre_encantador'], elementos: ['runa'] },
  },
  {
    id: 'alquimista',
    nome: 'Alquimista',
    personagem: 'Zubi da Retorta',
    descricao: 'Mistura poções, bombas e um homúnculo. Água + Arcano.',
    ensina: 'Ofício e magia na mesma ficha, cada um com seus pontos.',
    papel: 'oficio',
    complexidade: 2,
    referencia: 'Ragnarok, ToS',
    elementos: { agua: 14, arcano: 14, vileza: 12 },
    escolas: { benca: 10, conjuracao: 10, evocacao: 8 },
    recursos: { mana: 10 },
    talentos: { mao_de_mestre: 3, olho_de_materiais: 3, area_ampliada: 1 },
    profissoes: { alquimista: 14, cozinheiro: 6, artesao: 4 },
    skill: sk({
      nome: 'Bomba Ácida',
      elemento: 'acido',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 1.8,
      area: circulo(6),
      capacidadeExigida: 'bomba_acida',
    }),
    promete: { arquetipos: ['alquimista'], elementos: ['acido', 'mare'] },
  },
  {
    id: 'invocador',
    nome: 'Invocador',
    personagem: 'Rydia do Elo',
    descricao: 'Chama entidades primordiais que lutam no seu lugar. Arcano + Vida + Morte.',
    ensina: 'Equilíbrio exige vida e morte no mesmo nível — receita oposta.',
    papel: 'invocador',
    complexidade: 2,
    referencia: 'FF (Summoner), ToS',
    elementos: { arcano: 18, vida: 17, morte: 17 },
    escolas: { evocacao: 14 },
    recursos: { mana: 12 },
    talentos: { colosso: 3, autonomia: 2, simbiose: 2 },
    skill: sk({
      nome: 'Invocar Esper',
      elemento: 'equilibrio',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 34,
      tempoConjuracaoSegundos: 3.5,
      capacidadeExigida: 'invocar_esper',
    }),
    promete: {
      arquetipos: ['invocador'],
      elementos: ['equilibrio', 'reencarnacao', 'alma', 'essencia'],
    },
  },

  // ======== as classes que o público desses jogos procura pelo nome ========
  {
    id: 'curandeiro_vodu',
    nome: 'Curandeiro Vodu',
    personagem: 'Mãe Jubá',
    descricao: 'Solta espíritos e feras doentes na cara do inimigo. Vileza + Vida.',
    ensina: 'Evocação e maldição na mesma ficha: o que invoca também apodrece.',
    papel: 'invocador',
    complexidade: 1,
    referencia: 'Diablo III (Witch Doctor)',
    elementos: { vileza: 14, vida: 14 },
    escolas: { evocacao: 13, maldicao: 9 },
    recursos: { mana: 10 },
    talentos: { enxame: 3, contagio: 2, simbiose: 2 },
    skill: sk({
      nome: 'Matilha Apodrecida',
      elemento: 'mutacao',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      capacidadeExigida: 'evocar_feras_doentes',
    }),
    promete: { arquetipos: ['curandeiro_vodu'], elementos: ['mutacao'] },
  },
  {
    id: 'cacador_das_sombras',
    nome: 'Caçador das Sombras',
    personagem: 'Vol\u2019jin da Encruzilhada',
    descricao: 'Hexa o inimigo e cura o aliado com a mesma mão. Sombra + Vida.',
    ensina: 'Bênção e Maldição juntas: a mesma magia serve aos dois lados.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'WarCraft III / WoW (Shadow Hunter)',
    elementos: { sombra: 14, vida: 14 },
    escolas: { maldicao: 11, benca: 11 },
    recursos: { mana: 10 },
    talentos: { aflicao_profunda: 2, vinculo_de_grupo: 2, persistencia: 2 },
    skill: sk({
      nome: 'Hexar',
      elemento: 'parasita',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      entrega: continuo(12),
      capacidadeExigida: 'hexar',
    }),
    promete: { arquetipos: ['cacador_das_sombras'], elementos: ['parasita'] },
  },
  {
    id: 'ninja',
    nome: 'Ninja',
    personagem: 'Sem-Rosto',
    descricao: 'Deixa um clone apanhando enquanto some. Marcial + Sombra.',
    ensina: 'Impacto imediato numa skill barata: some antes da resposta.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'FF, Ragnarok, Tree of Savior',
    elementos: { marcial: 14, sombra: 14 },
    escolas: { combate_fisico: 13 },
    recursos: { furia: 8, mana: 6 },
    talentos: { impacto_imediato: 3, sequencia_marcial: 2, conjuracao_rapida: 2 },
    skill: sk({
      nome: 'Clone de Sombra',
      elemento: 'lamina_oculta',
      escola: 'combate_fisico',
      fontes: [fonte('furia', 60), fonte('mana', 40)],
      energia: 26,
      tempoConjuracaoSegundos: 0.9,
      alcanceMetros: 0,
      capacidadeExigida: 'clone_de_sombra',
    }),
    promete: { arquetipos: ['ninja'], elementos: ['lamina_oculta'] },
  },
  {
    id: 'samurai',
    nome: 'Samurai',
    personagem: 'Ronin do Vale Seco',
    descricao: 'Decide o corte antes de sacar a lâmina. Marcial + Ar.',
    ensina: 'Ressonância recompensa quem repete o mesmo gesto sem errar o ritmo.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'FF, Ragnarok',
    elementos: { marcial: 14, ar: 14 },
    escolas: { combate_fisico: 13 },
    recursos: { ressonancia: 12 },
    talentos: { golpe_devastador: 3, afinacao: 3, impacto_imediato: 2 },
    skill: sk({
      nome: 'Iaido',
      elemento: 'esgrima',
      escola: 'combate_fisico',
      fontes: [fonte('ressonancia')],
      energia: 28,
      tempoConjuracaoSegundos: 1.2,
      alcanceMetros: 0,
      capacidadeExigida: 'iaido',
    }),
    promete: { arquetipos: ['samurai'], elementos: ['esgrima'] },
  },
  {
    id: 'cavaleiro_negro',
    nome: 'Cavaleiro Negro',
    personagem: 'Cecil, antes do amanhecer',
    descricao: 'Paga com a própria vida por cada golpe. Marcial + Morte.',
    ensina: 'Soullink cobra em vida o que a mana cobraria em tempo.',
    papel: 'linha_de_frente',
    complexidade: 1,
    referencia: 'Final Fantasy (Dark Knight)',
    elementos: { marcial: 14, morte: 14 },
    escolas: { combate_fisico: 13 },
    recursos: { soullink: 12 },
    talentos: { golpe_devastador: 3, pacto_de_sangue: 3, elo_profundo: 2 },
    skill: sk({
      nome: 'Golpe Sombrio',
      elemento: 'fio_funebre',
      escola: 'combate_fisico',
      fontes: [fonte('soullink')],
      energia: 30,
      tempoConjuracaoSegundos: 1.3,
      alcanceMetros: 0,
      capacidadeExigida: 'golpe_sombrio',
    }),
    promete: { arquetipos: ['cavaleiro_negro'], elementos: ['fio_funebre'] },
  },
  {
    id: 'cacador_de_demonios',
    nome: 'Caçador de Demônios',
    personagem: 'Ilyra de Duas Bestas',
    descricao: 'Vira a maldição do inimigo contra ele, de longe. Marcial + Vileza.',
    ensina: 'Longo Alcance com elemento marcial: balestra, não feitiço.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'Diablo III, WoW',
    elementos: { marcial: 14, vileza: 14 },
    escolas: { longo_alcance: 13, combate_fisico: 9 },
    recursos: { furia: 10 },
    talentos: { rajada: 3, sede_de_batalha: 2, alcance_estendido: 2 },
    skill: sk({
      nome: 'Balestra Dupla',
      elemento: 'serrilha',
      escola: 'longo_alcance',
      fontes: [fonte('furia')],
      energia: 28,
      tempoConjuracaoSegundos: 1.4,
      alcanceMetros: 30,
      capacidadeExigida: 'balestra_dupla',
    }),
    promete: { arquetipos: ['cacador_de_demonios'], elementos: ['serrilha'] },
  },
  {
    id: 'sabio',
    nome: 'Sábio',
    personagem: 'Mestre Odilon',
    descricao: 'Empresta elemento à arma dos outros. Ar + Arcano.',
    ensina: 'Suporte que não cura: melhora a skill de quem está do seu lado.',
    papel: 'suporte',
    complexidade: 1,
    referencia: 'Ragnarok (Sage), ToS',
    elementos: { ar: 14, arcano: 14 },
    escolas: { conjuracao: 13, benca: 9 },
    recursos: { mana: 12 },
    talentos: { area_ampliada: 1, fluxo_constante: 2, persistencia: 3 },
    skill: sk({
      nome: 'Muro Mágico',
      elemento: 'eter',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      area: circulo(6),
      entrega: continuo(14),
      capacidadeExigida: 'muro_magico',
    }),
    promete: { arquetipos: ['sabio'], elementos: ['eter'] },
  },
  {
    id: 'vinculador_de_almas',
    nome: 'Vinculador de Almas',
    personagem: 'Irmã Amarra',
    descricao: 'Amarra a alma de quem luta ao seu lado e divide o dano. Arcano + Morte.',
    ensina: 'Soullink como recurso de SUPORTE, não de sacrifício.',
    papel: 'suporte',
    complexidade: 1,
    referencia: 'Ragnarok (Soul Linker)',
    elementos: { arcano: 14, morte: 14 },
    escolas: { benca: 13 },
    recursos: { soullink: 14 },
    talentos: { vinculo_de_grupo: 3, elo_profundo: 3, area_ampliada: 1 },
    skill: sk({
      nome: 'Vincular Espírito',
      elemento: 'alma',
      escola: 'benca',
      fontes: [fonte('soullink')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      area: circulo(6),
      entrega: continuo(16),
      capacidadeExigida: 'vincular_espirito',
    }),
    promete: { arquetipos: ['vinculador_de_almas'], elementos: ['alma'] },
  },

  // ======== arquétipos que existiam sem nenhuma classe pronta ========
  {
    id: 'cavalaria_negra',
    nome: 'Cavalaria Negra',
    personagem: 'Reiter da Névoa',
    descricao: 'Atira montado, em salva, e some antes da resposta. Longo Alcance + Fúria.',
    ensina: 'Montaria: capturar, domar e usar a fera como veículo da skill.',
    papel: 'foco',
    complexidade: 2,
    referencia: 'Tree of Savior (Schwarzer Reiter)',
    elementos: { marcial: 12, eletricidade: 10, vida: 12, terra: 12 },
    escolas: { longo_alcance: 13, combate_fisico: 9, evocacao: 8 },
    recursos: { furia: 12 },
    talentos: { rajada: 3, montaria: 1, vinculo_primal: 1, alcance_estendido: 1 },
    bestiario: [{ criaturaId: 'javali', vinculo: 2 }],
    skill: sk({
      nome: 'Salva de Cavalaria',
      elemento: 'aco_voltaico',
      escola: 'longo_alcance',
      fontes: [fonte('furia')],
      energia: 28,
      tempoConjuracaoSegundos: 1.5,
      alcanceMetros: 25,
      montariaId: 'javali',
      capacidadeExigida: 'salva_de_cavalaria',
    }),
    promete: { arquetipos: ['cavalaria_negra'], elementos: ['aco_voltaico'] },
  },
  {
    id: 'mago_vermelho',
    nome: 'Mago Vermelho',
    personagem: 'Vermelha de Cornélia',
    descricao: 'Conjura duas vezes e ainda saca a espada. Fogo + Arcano.',
    ensina: 'Espalhar por três escolas custa profundidade e compra versatilidade.',
    papel: 'controle',
    complexidade: 2,
    referencia: 'Final Fantasy (Red Mage)',
    elementos: { fogo: 14, arcano: 14, marcial: 10 },
    escolas: { conjuracao: 10, benca: 9, maldicao: 9, combate_fisico: 6 },
    recursos: { mana: 12 },
    talentos: { metamagia_gemea: 3, endossar_elemento: 2, fluxo_constante: 2 },
    skill: sk({
      nome: 'Conjuração Dupla',
      elemento: 'fogo_feiticeiro',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 1.8,
      capacidadeExigida: 'conjuracao_dupla',
    }),
    promete: { arquetipos: ['mago_vermelho'], elementos: ['fogo_feiticeiro', 'arsenal'] },
  },
  {
    id: 'feiticeiro_de_cartas',
    nome: 'Feiticeiro de Cartas',
    personagem: 'O Colecionador',
    descricao: 'Sela o monstro numa carta e o solta quando quiser. Evocação pura.',
    ensina: 'Bestiário e evocação juntos: a criatura capturada vira a skill.',
    papel: 'invocador',
    complexidade: 2,
    referencia: 'Tree of Savior (Sorcerer)',
    elementos: { arcano: 14, morte: 10, vileza: 12 },
    escolas: { evocacao: 16 },
    recursos: { mana: 12 },
    talentos: { colosso: 3, vinculo_primal: 1, autonomia: 2 },
    bestiario: [{ criaturaId: 'demonio_maior', vinculo: 1 }],
    skill: sk({
      nome: 'Invocar Chefe',
      elemento: 'alma',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 34,
      tempoConjuracaoSegundos: 3,
      capacidadeExigida: 'invocar_chefe',
      evocacao: { modo: 'capturada', criaturaId: 'demonio_maior' },
    }),
    promete: { arquetipos: ['feiticeiro_de_cartas'], elementos: ['alma'] },
  },
  {
    id: 'tecelao_de_sangue',
    nome: 'Tecelão de Sangue',
    personagem: 'Pé-de-Pena',
    descricao: 'Tira o sangue do inimigo e costura com ele. Maldição + Soullink.',
    ensina: 'Maldição que cura você enquanto drena o outro.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'Tree of Savior (Featherfoot)',
    elementos: { morte: 12, vileza: 12 },
    escolas: { maldicao: 13 },
    recursos: { soullink: 14 },
    talentos: { aflicao_profunda: 3, pacto_de_sangue: 3, elo_profundo: 2 },
    skill: sk({
      nome: 'Transfusão',
      elemento: 'praga',
      escola: 'maldicao',
      fontes: [fonte('soullink')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      entrega: continuo(14),
      capacidadeExigida: 'transfusao',
    }),
    promete: { arquetipos: ['tecelao_de_sangue'], elementos: ['praga'] },
  },
  {
    id: 'cabalista',
    nome: 'Cabalista',
    personagem: 'Escriba Menahem',
    descricao: 'Soma números até a vida do aliado dobrar. Arcano + Terra + Luz.',
    ensina: 'Numerologia como suporte: multiplica em vez de somar.',
    papel: 'suporte',
    complexidade: 2,
    referencia: 'Tree of Savior (Kabbalist)',
    elementos: { arcano: 12, terra: 12, luz: 12 },
    escolas: { benca: 13 },
    recursos: { mana: 12 },
    talentos: { exaltacao: 3, vinculo_de_grupo: 3, area_ampliada: 1 },
    skill: sk({
      nome: 'Ampliar Vida',
      elemento: 'cristal',
      escola: 'benca',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
      entrega: continuo(16),
      capacidadeExigida: 'ampliar_vida',
    }),
    promete: { arquetipos: ['cabalista'], elementos: ['cristal', 'runa'] },
  },
  {
    id: 'inquisidor',
    nome: 'Inquisidor',
    personagem: 'Padre Tomás',
    descricao: 'Sentencia o enfraquecido e executa a sentença. Luz + Morte.',
    ensina: 'Maldição com Luz: a punição é sagrada, não sombria.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'Diablo, WoW, Ragnarok',
    elementos: { luz: 14, morte: 14 },
    escolas: { maldicao: 11, benca: 8 },
    recursos: { fe: 12 },
    talentos: { aflicao_profunda: 3, devocao: 3, impacto_imediato: 2 },
    skill: sk({
      nome: 'Sentença Final',
      elemento: 'julgamento',
      escola: 'maldicao',
      fontes: [fonte('fe')],
      energia: 28,
      tempoConjuracaoSegundos: 2,
      capacidadeExigida: 'sentenca_final',
    }),
    promete: { arquetipos: ['inquisidor'], elementos: ['julgamento'] },
  },
  {
    id: 'mestre_das_runas',
    nome: 'Mestre das Runas',
    personagem: 'Gravador Hjalmar',
    descricao: 'Grava runas no chão que continuam agindo depois de você sair. Arcano + Luz.',
    ensina: 'Persistência: o efeito dura mais que a conjuração.',
    papel: 'linha_de_frente',
    complexidade: 1,
    referencia: 'Ragnarok (Rune Knight)',
    elementos: { arcano: 14, luz: 14, marcial: 10 },
    escolas: { benca: 11, combate_fisico: 9 },
    recursos: { mana: 10 },
    talentos: { persistencia: 3, area_ampliada: 1, postura_inabalavel: 2 },
    skill: sk({
      nome: 'Gravar Runas',
      elemento: 'runa',
      escola: 'benca',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(6),
      entrega: continuo(20),
      capacidadeExigida: 'gravar_runas',
    }),
    promete: { arquetipos: ['mestre_das_runas'], elementos: ['runa'] },
  },
  {
    id: 'corruptor',
    nome: 'Corruptor',
    personagem: 'O Jardineiro Errado',
    descricao: 'Transforma o inimigo em algo que luta contra os próprios aliados. Vileza + Vida.',
    ensina: 'Controle por conversão: o alvo vira problema do outro lado.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'WoW, Diablo',
    elementos: { vileza: 14, vida: 14 },
    escolas: { maldicao: 11 },
    recursos: { mana: 10 },
    talentos: { contagio: 3, dano_ao_longo_do_tempo: 3 },
    skill: sk({
      nome: 'Maldição Mutante',
      elemento: 'mutacao',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      entrega: continuo(14),
      capacidadeExigida: 'maldicao_mutante',
    }),
    promete: { arquetipos: ['corruptor'], elementos: ['mutacao'] },
  },
  {
    id: 'olho_da_tormenta',
    nome: 'Olho da Tormenta',
    personagem: 'Flecha de Vento',
    descricao: 'Solta flechas-relâmpago que não erram. Ar + Eletricidade.',
    ensina: 'Longo Alcance com elemento de área: cada flecha carrega tempestade.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'Ragnarok (Sniper), WoW (Hunter)',
    elementos: { ar: 13, eletricidade: 13 },
    escolas: { longo_alcance: 13 },
    recursos: { mana: 10 },
    talentos: { olho_de_aguia: 3, alcance_estendido: 3 },
    skill: sk({
      nome: 'Flecha-Relâmpago',
      elemento: 'tempestade',
      escola: 'longo_alcance',
      fontes: [fonte('mana')],
      energia: 26,
      tempoConjuracaoSegundos: 1.6,
      alcanceMetros: 35,
      capacidadeExigida: 'flecha_relampago',
    }),
    promete: { arquetipos: ['olho_da_tormenta'], elementos: ['tempestade'] },
  },
  {
    id: 'engenheiro_galvanico',
    nome: 'Engenheiro Galvânico',
    personagem: 'Doutora Volt',
    descricao: 'Costura carne morta e acorda com um raio. Eletricidade + Morte.',
    ensina: 'Evocação de constructo: você fabrica o que invoca.',
    papel: 'invocador',
    complexidade: 1,
    referencia: 'Tree of Savior, Frankenstein',
    elementos: { eletricidade: 14, morte: 14 },
    escolas: { evocacao: 13 },
    recursos: { mana: 10 },
    talentos: { colosso: 3, simbiose: 2, evolucao_da_fera: 2 },
    skill: sk({
      nome: 'Constructo Galvânico',
      elemento: 'galvanismo',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 2.5,
      capacidadeExigida: 'evocar_constructos_galvanicos',
    }),
    promete: { arquetipos: ['engenheiro_galvanico'], elementos: ['galvanismo'] },
  },
  {
    id: 'senhor_dos_mortos_vis',
    nome: 'Senhor dos Mortos Vis',
    personagem: 'O Sepultador',
    descricao: 'Invoca demônios que já morreram uma vez. Morte + Vileza.',
    ensina: 'Dois elementos aliados aprofundam o que cada um já fazia sozinho.',
    papel: 'invocador',
    complexidade: 2,
    referencia: 'Diablo, WoW',
    elementos: { morte: 16, vileza: 16 },
    escolas: { evocacao: 16 },
    recursos: { mana: 12 },
    talentos: { enxame: 4, comando: 2, simbiose: 2 },
    skill: sk({
      nome: 'Legião Profana',
      elemento: 'praga',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 32,
      tempoConjuracaoSegundos: 3,
      capacidadeExigida: 'evocar_demonios_mortos',
    }),
    promete: { arquetipos: ['senhor_dos_mortos_vis'], elementos: ['praga'] },
  },
  {
    id: 'escriba_do_pacto',
    nome: 'Escriba do Pacto',
    personagem: 'Notário Vhess',
    descricao: 'Redige contratos que a realidade é obrigada a cumprir. Arcano + Vileza.',
    ensina: 'Ofício e maldição juntos: o contrato é um item que você fabrica.',
    papel: 'oficio',
    complexidade: 2,
    referencia: 'D&D (Warlock), PoE',
    elementos: { arcano: 14, vileza: 14 },
    escolas: { maldicao: 13 },
    recursos: { mana: 12 },
    talentos: { mao_de_mestre: 3, aflicao_profunda: 2, assinatura_do_artesao: 1 },
    profissoes: { escriba: 14, encantador: 8 },
    skill: sk({
      nome: 'Cobrar o Preço',
      elemento: 'pacto',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      entrega: continuo(16),
      capacidadeExigida: 'cobrar_o_preco',
    }),
    promete: { arquetipos: ['escriba_do_pacto'], elementos: ['pacto'] },
  },
  {
    id: 'guardiao_do_ciclo',
    nome: 'Guardião do Ciclo',
    personagem: 'O Que Gira',
    descricao: 'Inverte cura em dano e maldição em bênção. Vida + Morte + Luz + Sombra.',
    ensina: 'Quatro elementos OPOSTOS dois a dois: a quádrupla mais tensa que existe.',
    papel: 'suporte',
    complexidade: 3,
    elementos: { vida: 13, morte: 13, luz: 13, sombra: 13 },
    escolas: { benca: 12, maldicao: 12 },
    recursos: { mana: 12, fe: 8 },
    talentos: { exaltacao: 3, aflicao_profunda: 3, area_ampliada: 2 },
    skill: sk({
      nome: 'Inverter Estado',
      elemento: 'ciclo',
      escola: 'benca',
      fontes: [fonte('mana', 60), fonte('fe', 40)],
      energia: 32,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(7),
      entrega: continuo(14),
      capacidadeExigida: 'inverter_estado',
    }),
    promete: { arquetipos: ['guardiao_do_ciclo'], elementos: ['ciclo'] },
  },

  // ==== a segunda leva do benchmark: pólvora, forma de fera e voz sombria ====
  {
    id: 'pistoleiro',
    nome: 'Pistoleiro',
    personagem: 'Rebe do Gatilho',
    descricao: 'Esvazia o tambor num alvo só e recarrega sem tirar a mira. Marcial + Fogo.',
    ensina: 'Pólvora em vez de feitiço: Longo Alcance com elemento marcial.',
    papel: 'foco',
    complexidade: 1,
    referencia: 'Ragnarok (Gunslinger), ToS (Musketeer), FF (Machinist)',
    elementos: { marcial: 15, fogo: 15 },
    escolas: { longo_alcance: 13 },
    recursos: { furia: 10 },
    talentos: { rajada: 3, alcance_estendido: 2, sede_de_batalha: 2 },
    skill: sk({
      nome: 'Rajada de Pólvora',
      elemento: 'forja',
      escola: 'longo_alcance',
      fontes: [fonte('furia')],
      energia: 28,
      tempoConjuracaoSegundos: 1.2,
      alcanceMetros: 28,
      capacidadeExigida: 'rajada_de_polvora',
    }),
    promete: { arquetipos: ['pistoleiro'], elementos: ['forja'] },
  },
  {
    id: 'metamorfo',
    nome: 'Metamorfo',
    personagem: 'Uril de Duas Peles',
    descricao: 'Vira a fera que domou e luta com as garras dela. Marcial + Terra + Vida.',
    ensina: 'Bestiário e combate juntos: a criatura domada vira a sua forma.',
    papel: 'linha_de_frente',
    complexidade: 2,
    referencia: 'WoW (Feral), Diablo II/IV (Druida), ToS',
    elementos: { marcial: 16, terra: 16, vida: 16 },
    escolas: { combate_fisico: 13, evocacao: 9 },
    recursos: { furia: 12 },
    talentos: { vinculo_primal: 1, instinto_de_caca: 3, postura_inabalavel: 2 },
    bestiario: [{ criaturaId: 'urso', vinculo: 3 }],
    skill: sk({
      nome: 'Assumir Forma de Fera',
      elemento: 'tita',
      escola: 'combate_fisico',
      fontes: [fonte('furia')],
      energia: 30,
      tempoConjuracaoSegundos: 1.5,
      alcanceMetros: 0,
      capacidadeExigida: 'assumir_forma_de_fera',
    }),
    promete: { arquetipos: ['metamorfo'], elementos: ['tita', 'flora'] },
  },
  {
    id: 'sacerdote_sombrio',
    nome: 'Sacerdote Sombrio',
    personagem: 'Irmão Silêncio',
    descricao: 'Esfola a mente do alvo e se cura com o que arranca. Arcano + Sombra.',
    ensina: 'Maldição que também é bênção: o dano volta como cura para você.',
    papel: 'controle',
    complexidade: 1,
    referencia: 'WoW (Shadow Priest)',
    elementos: { arcano: 15, sombra: 15 },
    escolas: { maldicao: 13, benca: 9 },
    recursos: { mana: 12 },
    talentos: { aflicao_profunda: 3, dano_ao_longo_do_tempo: 3, fluxo_constante: 2 },
    skill: sk({
      nome: 'Verbo Sombrio',
      elemento: 'ocultismo',
      escola: 'maldicao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2,
      entrega: continuo(14),
      capacidadeExigida: 'verbo_sombrio',
    }),
    promete: { arquetipos: ['sacerdote_sombrio'], elementos: ['ocultismo'] },
  },
  {
    id: 'draconato',
    nome: 'Draconato',
    personagem: 'Escama de Bronze',
    descricao: 'Segura o sopro no peito e solta em cone quanto mais esperar. Fogo + Ar + Vida + Marcial.',
    ensina: 'Tempo de conjuração longo rende mais poder: o orçamento cresce com √tempo.',
    papel: 'area',
    complexidade: 3,
    referencia: 'WoW (Evoker), FF',
    elementos: { fogo: 20, ar: 20, vida: 20, marcial: 20 },
    escolas: { conjuracao: 14 },
    recursos: { mana: 12 },
    talentos: { canalizacao_profunda: 3, area_ampliada: 3 },
    skill: sk({
      nome: 'Sopro Carregado',
      elemento: 'sopro_do_dragao',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 40,
      tempoConjuracaoSegundos: 4,
      area: circulo(10),
      capacidadeExigida: 'sopro_carregado',
    }),
    promete: { arquetipos: ['draconato'], elementos: ['sopro_do_dragao', 'fenix'] },
  },
  {
    id: 'comandante_de_guerra',
    nome: 'Comandante de Guerra',
    personagem: 'Capitã Vasla',
    descricao: 'Brada uma ordem que faz a linha inteira avançar junto. Ar + Luz + Vida + Marcial.',
    ensina: 'Suporte que não cura: a bênção move o grupo em vez de sarar.',
    papel: 'linha_de_frente',
    complexidade: 3,
    referencia: 'Ragnarok (Royal Guard), WoW (Warrior)',
    elementos: { ar: 19, luz: 19, vida: 19, marcial: 19 },
    escolas: { benca: 13, combate_fisico: 11 },
    recursos: { furia: 10, fe: 8 },
    talentos: { vinculo_de_grupo: 3, ritmo_de_guerra: 3, area_ampliada: 3 },
    skill: sk({
      nome: 'Brado de Comando',
      elemento: 'arauto',
      escola: 'benca',
      fontes: [fonte('furia', 60), fonte('fe', 40)],
      energia: 32,
      tempoConjuracaoSegundos: 2,
      area: circulo(10),
      entrega: continuo(14),
      capacidadeExigida: 'brado_de_comando',
    }),
    promete: { arquetipos: ['comandante_de_guerra'], elementos: ['arauto', 'bravura'] },
  },
  {
    id: 'punho_ascetico',
    nome: 'Punho Ascético',
    personagem: 'Irmão Vazio',
    descricao: 'Concentra tudo num soco só e fica oco depois dele. Vida + Marcial + Gravidade.',
    ensina: 'Impacto Imediato no extremo: todo o orçamento num golpe.',
    papel: 'foco',
    complexidade: 2,
    referencia: 'Ragnarok (Sura / Asura Strike)',
    elementos: { vida: 17, marcial: 17, gravidade: 17 },
    escolas: { combate_fisico: 14 },
    recursos: { ressonancia: 14 },
    talentos: { impacto_imediato: 3, afinacao: 3, golpe_devastador: 3 },
    skill: sk({
      nome: 'Punho do Abismo',
      elemento: 'punho_gravitico',
      escola: 'combate_fisico',
      fontes: [fonte('ressonancia')],
      energia: 36,
      tempoConjuracaoSegundos: 2.5,
      alcanceMetros: 0,
      capacidadeExigida: 'punho_do_abismo',
    }),
    promete: { arquetipos: ['punho_ascetico'], elementos: ['punho_gravitico', 'vigor'] },
  },
  {
    id: 'arqueiro_sombrio',
    nome: 'Arqueiro Sombrio',
    personagem: 'Sylva da Trilha Fria',
    descricao: 'Atira uma flecha que ergue o morto que ela matou. Ar + Morte + Vida.',
    ensina: 'Longo Alcance com Maldição: o tiro deixa efeito depois do impacto.',
    papel: 'foco',
    complexidade: 2,
    referencia: 'WarCraft III (Dark Ranger), Ragnarok',
    elementos: { ar: 16, morte: 16, vida: 16 },
    escolas: { longo_alcance: 13, maldicao: 9 },
    recursos: { soullink: 10, mana: 6 },
    talentos: { olho_de_aguia: 3, alcance_estendido: 2, elo_profundo: 2 },
    skill: sk({
      nome: 'Flecha Negra',
      elemento: 'requiem',
      escola: 'longo_alcance',
      fontes: [fonte('soullink', 60), fonte('mana', 40)],
      energia: 28,
      tempoConjuracaoSegundos: 1.8,
      alcanceMetros: 30,
      capacidadeExigida: 'flecha_negra',
    }),
    promete: { arquetipos: ['arqueiro_sombrio'], elementos: ['requiem', 'miasma'] },
  },
  {
    id: 'crepuscular',
    nome: 'Crepuscular',
    personagem: 'A Fronteira',
    descricao: 'Revela e oculta no mesmo gesto, e troca qual dos dois no meio. Luz + Sombra.',
    ensina: 'Dois elementos OPOSTOS: a tensão custa mais e entrega mais.',
    papel: 'controle',
    complexidade: 2,
    elementos: { luz: 17, sombra: 17 },
    escolas: { conjuracao: 13 },
    recursos: { mana: 12 },
    talentos: { area_ampliada: 2, persistencia: 3, metamagia_gemea: 2 },
    skill: sk({
      nome: 'Alternar Faces',
      elemento: 'crepusculo',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 30,
      tempoConjuracaoSegundos: 2.2,
      area: circulo(7),
      entrega: continuo(12),
      capacidadeExigida: 'alternar_faces',
    }),
    promete: { arquetipos: ['crepuscular'], elementos: ['crepusculo'] },
  },
  {
    id: 'heresiarca',
    nome: 'Heresiarca',
    personagem: 'O Bispo Torto',
    descricao: 'Abençoa com uma luz que cobra juros de quem aceita. Luz + Vileza.',
    ensina: 'Bênção e Maldição na mesma skill: o buff tem preço embutido.',
    papel: 'suporte',
    complexidade: 1,
    referencia: 'Diablo, ToS (Zealot)',
    elementos: { luz: 15, vileza: 15 },
    escolas: { benca: 11, maldicao: 11 },
    recursos: { fe: 12 },
    talentos: { exaltacao: 3, aflicao_profunda: 2, area_ampliada: 1 },
    skill: sk({
      nome: 'Milagre Falso',
      elemento: 'heresia',
      escola: 'benca',
      fontes: [fonte('fe')],
      energia: 26,
      tempoConjuracaoSegundos: 2,
      area: circulo(5),
      entrega: continuo(14),
      capacidadeExigida: 'milagre_falso',
    }),
    promete: { arquetipos: ['heresiarca'], elementos: ['heresia'] },
  },
  {
    id: 'trovador_sombrio',
    nome: 'Trovador Sombrio',
    personagem: 'A Corda Torta',
    descricao: 'Toca fora do tom até o inimigo perder o próprio ritmo. Ar + Vida + Vileza.',
    ensina: 'A contraparte do Menestrel: a mesma canção, virada do avesso.',
    papel: 'controle',
    complexidade: 2,
    referencia: 'Ragnarok (Wanderer), ToS',
    elementos: { ar: 17, vida: 17, vileza: 17 },
    escolas: { maldicao: 13 },
    recursos: { ressonancia: 12, mana: 6 },
    talentos: { afinacao: 3, aflicao_profunda: 3, area_ampliada: 2 },
    skill: sk({
      nome: 'Canção Dissonante',
      elemento: 'dissonancia',
      escola: 'maldicao',
      fontes: [fonte('ressonancia', 70), fonte('mana', 30)],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(8),
      entrega: continuo(16),
      capacidadeExigida: 'cancao_dissonante',
    }),
    promete: { arquetipos: ['trovador_sombrio'], elementos: ['dissonancia'] },
  },
  {
    id: 'tecelao_de_abominacoes',
    nome: 'Tecelão de Abominações',
    personagem: 'A Costureira',
    descricao: 'Costura pedaços de vários cadáveres num monstro só. Morte + Sombra + Vileza.',
    ensina: 'Colosso: uma invocação grande em vez de um enxame.',
    papel: 'invocador',
    complexidade: 2,
    referencia: 'WoW (Abomination), Diablo II',
    elementos: { morte: 17, sombra: 17, vileza: 17 },
    escolas: { evocacao: 16 },
    recursos: { mana: 12 },
    talentos: { colosso: 4, evolucao_da_fera: 2, comando: 2 },
    skill: sk({
      nome: 'Costurar Horror',
      elemento: 'abominacao',
      escola: 'evocacao',
      fontes: [fonte('mana')],
      energia: 34,
      tempoConjuracaoSegundos: 3,
      capacidadeExigida: 'evocar_abominacoes',
    }),
    promete: { arquetipos: ['horologista_do_horror'], elementos: ['abominacao', 'espectro'] },
  },
  {
    id: 'feiticeiro_do_abismo',
    nome: 'Feiticeiro do Abismo',
    personagem: 'A Que Afunda',
    descricao: 'Afunda o campo em pressão abissal que cega e esmaga junto. Água + Sombra.',
    ensina: 'Um par simples com escola profunda rivaliza com combinações grandes.',
    papel: 'area',
    complexidade: 1,
    referencia: 'WarCraft III (Naga), FF (Leviatã)',
    elementos: { agua: 15, sombra: 15 },
    escolas: { conjuracao: 13 },
    recursos: { mana: 12 },
    talentos: { area_ampliada: 3, dano_ao_longo_do_tempo: 2 },
    skill: sk({
      nome: 'Pressão Abissal',
      elemento: 'abismo',
      escola: 'conjuracao',
      fontes: [fonte('mana')],
      energia: 28,
      tempoConjuracaoSegundos: 2.5,
      area: circulo(9),
      capacidadeExigida: 'conjurar_abismo',
    }),
    promete: { arquetipos: ['feiticeiro_do_abismo'], elementos: ['abismo'] },
  },
];

export const PRESETS_POR_ID = new Map(PRESETS.map((p) => [p.id, p]));
